criteria:
    path:     /
    defaults: { _controller: "EsteiNotatorBundle:Criteria:index" }

criteria_show:
    path:     /{id}/show
    defaults: { _controller: "EsteiNotatorBundle:Criteria:show" }

criteria_new:
    path:     /new
    defaults: { _controller: "EsteiNotatorBundle:Criteria:new" }

criteria_create:
    path:     /create
    defaults: { _controller: "EsteiNotatorBundle:Criteria:create" }
    requirements: { _method: post }

criteria_edit:
    path:     /{id}/edit
    defaults: { _controller: "EsteiNotatorBundle:Criteria:edit" }

criteria_update:
    path:     /{id}/update
    defaults: { _controller: "EsteiNotatorBundle:Criteria:update" }
    requirements: { _method: post|put }

criteria_delete:
    path:     /{id}/delete
    defaults: { _controller: "EsteiNotatorBundle:Criteria:delete" }
    requirements: { _method: post|delete }
