Step:
    type: entity
    table: step
    indexes:
        fk_step_scale_idx:
            columns:
                - scale_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        shortname:
            type: string
            nullable: true
            length: 10
            fixed: false
        content:
            type: text
            nullable: true
            length: 65535
            fixed: false
        position:
            type: integer
            nullable: false
            unsigned: false
    manyToOne:
        scale:
            targetEntity: Scale
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                scale_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
