Student:
    type: entity
    table: student
    indexes:
        fk_student_user1_idx:
            columns:
                - user_id
        fk_student_class1_idx:
            columns:
                - classroom_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        classroom:
            targetEntity: Classroom
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                classroom_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
