User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: true
            length: 45
            fixed: false
        lastname:
            type: string
            nullable: true
            length: 45
            fixed: false
        login:
            type: string
            nullable: true
            length: 45
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
